#define Order 1
#define RANDOM_LENGTH ((Order * Order + Order) * 32)
unsigned short random_table[RANDOM_LENGTH / 2];
unsigned short sbx0[Order];
unsigned short sbx1[Order];
unsigned short sbx2[Order];
unsigned short sbx3[Order];
unsigned short sbx4[Order];
unsigned short sbx5[Order];
unsigned short sbx6[Order];
unsigned short sbx7[Order];
unsigned int sbx7_for_online[ORDER];

unsigned short sby0[Order]={0};
unsigned short sby1[Order]={0};
unsigned short sby2[Order]={0};
unsigned short sby3[Order]={0};
unsigned short sby4[Order]={0};
unsigned short sby5[Order]={0};
unsigned short sby6[Order]={0};
unsigned short sby7[Order]={0};
unsigned short sby8[Order]={0};
unsigned short sby9[Order]={0};
unsigned short sby10[Order]={0};
unsigned short sby11[Order]={0};
unsigned short sby12[Order]={0};
unsigned short sby13[Order]={0};
unsigned short sby14[Order]={0};
unsigned short sby15[Order]={0};
unsigned short sby16[Order]={0};
unsigned short sby17[Order]={0};
unsigned short sby18[Order]={0};
unsigned short sby19[Order]={0};
unsigned short sby20[Order]={0};
unsigned short sby21[Order]={0};

unsigned short sbt0[Order]={0};
unsigned short sbt1[Order]={0};
unsigned short sbt2[Order]={0};
unsigned short sbt3[Order]={0};
unsigned short sbt4[Order]={0};
unsigned short sbt5[Order]={0};
unsigned short sbt6[Order]={0};
unsigned short sbt7[Order]={0};
unsigned short sbt8[Order]={0};
unsigned short sbt9[Order]={0};
unsigned short sbt10[Order]={0};
unsigned short sbt11[Order]={0};
unsigned short sbt12[Order]={0};
unsigned short sbt13[Order]={0};
unsigned short sbt14[Order]={0};
unsigned short sbt15[Order]={0};
unsigned short sbt16[Order]={0};
unsigned short sbt17[Order]={0};
unsigned short sbt18[Order]={0};
unsigned short sbt19[Order]={0};
unsigned short sbt20[Order]={0};
unsigned short sbt21[Order]={0};
unsigned short sbt22[Order]={0};
unsigned short sbt23[Order]={0};
unsigned short sbt24[Order]={0};
unsigned short sbt25[Order]={0};
unsigned short sbt26[Order]={0};
unsigned short sbt27[Order]={0};
unsigned short sbt28[Order]={0};
unsigned short sbt29[Order]={0};
unsigned short sbt30[Order]={0};
unsigned short sbt31[Order]={0};
unsigned short sbt32[Order]={0};
unsigned short sbt33[Order]={0};
unsigned short sbt34[Order]={0};
unsigned short sbt35[Order]={0};
unsigned short sbt36[Order]={0};
unsigned short sbt37[Order]={0};
unsigned short sbt38[Order]={0};
unsigned short sbt39[Order]={0};
unsigned short sbt40[Order]={0};
unsigned short sbt41[Order]={0};
unsigned short sbt42[Order]={0};
unsigned short sbt43[Order]={0};
unsigned short sbt44[Order]={0};
unsigned short sbt45[Order]={0};
unsigned short sbt46[Order]={0};
unsigned short sbt47[Order]={0};
unsigned short sbt48[Order]={0};
unsigned short sbt49[Order]={0};
unsigned short sbt50[Order]={0};
unsigned short sbt51[Order]={0};
unsigned short sbt52[Order]={0};
unsigned short sbt53[Order]={0};
unsigned short sbt54[Order]={0};
unsigned short sbt55[Order]={0};
unsigned short sbt56[Order]={0};
unsigned short sbt57[Order]={0};
unsigned short sbt58[Order]={0};
unsigned short sbt59[Order]={0};
unsigned short sbt60[Order]={0};
unsigned short sbt61[Order]={0};
unsigned short sbt62[Order]={0};
unsigned short sbt63[Order]={0};
unsigned short sbt64[Order]={0};
unsigned short sbt65[Order]={0};
unsigned short sbt66[Order]={0};
unsigned short sbt67[Order]={0};

unsigned short sbs0[Order]={0};
unsigned short sbs1[Order]={0};
unsigned short sbs2[Order]={0};
unsigned short sbs3[Order]={0};
unsigned short sbs4[Order]={0};
unsigned short sbs5[Order]={0};
unsigned short sbs6[Order]={0};
unsigned short sbs7[Order]={0};


unsigned short sbz0[Order]={0};
unsigned short sbz1[Order]={0};
unsigned short sbz2[Order]={0};
unsigned short sbz3[Order]={0};
unsigned short sbz4[Order]={0};
unsigned short sbz5[Order]={0};
unsigned short sbz6[Order]={0};
unsigned short sbz8[Order]={0};
unsigned short sbz7[Order]={0};
unsigned short sbz9[Order]={0};
unsigned short sbz10[Order]={0};
unsigned short sbz11[Order]={0};
unsigned short sbz12[Order]={0};
unsigned short sbz13[Order]={0};
unsigned short sbz14[Order]={0};
unsigned short sbz15[Order]={0};
unsigned short sbz16[Order]={0};
unsigned short sbz17[Order]={0};

unsigned short sband1ty12[Order];
unsigned short sband1ty15[Order];
unsigned short sband1tr[Order];
unsigned short sband2ty3[Order];
unsigned short sband2ty6[Order];
unsigned short sband2tr[Order];
unsigned short sband3ty4[Order];
unsigned short sband3tx7[Order];
unsigned short sband3tr[Order];
unsigned short sband4ty13[Order];
unsigned short sband4ty16[Order];
unsigned short sband4tr[Order];
unsigned short sband5ty5[Order];
unsigned short sband5ty1[Order];
unsigned short sband5tr[Order];
unsigned short sband6ty2[Order];
unsigned short sband6ty7[Order];
unsigned short sband6tr[Order];
unsigned short sband7ty9[Order];
unsigned short sband7ty11[Order];
unsigned short sband7tr[Order];
unsigned short sband8ty14[Order];
unsigned short sband8ty17[Order];
unsigned short sband8tr[Order];
unsigned short sband9ty8[Order];
unsigned short sband9ty10[Order];
unsigned short sband9tr[Order];
unsigned short sband10tt21[Order];
unsigned short sband10tt23[Order];
unsigned short sband10tr[Order];
unsigned short sband11tt25[Order];
unsigned short sband11tt27[Order];
unsigned short sband11tr[Order];
unsigned short sband12tt31[Order];
unsigned short sband12tt30[Order];
unsigned short sband12tr[Order];
unsigned short sband13tt29[Order];
unsigned short sband13ty2[Order];
unsigned short sband13tr[Order];
unsigned short sband14tt24[Order];
unsigned short sband14tt35[Order];
unsigned short sband14tr[Order];
unsigned short sband15tt29[Order];
unsigned short sband15tt38[Order];
unsigned short sband15tr[Order];
unsigned short sband16tt29[Order];
unsigned short sband16ty7[Order];
unsigned short sband16tr[Order];
unsigned short sband17tt44[Order];
unsigned short sband17ty15[Order];
unsigned short sband17tr[Order];
unsigned short sband18tt37[Order];
unsigned short sband18ty6[Order];
unsigned short sband18tr[Order];
unsigned short sband19tt33[Order];
unsigned short sband19tx7[Order];
unsigned short sband19tr[Order];
unsigned short sband20tt43[Order];
unsigned short sband20ty16[Order];
unsigned short sband20tr[Order];
unsigned short sband21tt40[Order];
unsigned short sband21ty1[Order];
unsigned short sband21tr[Order];
unsigned short sband22tt42[Order];
unsigned short sband22ty11[Order];
unsigned short sband22tr[Order];
unsigned short sband23tt45[Order];
unsigned short sband23ty17[Order];
unsigned short sband23tr[Order];
unsigned short sband24tt41[Order];
unsigned short sband24ty10[Order];
unsigned short sband24tr[Order];
unsigned short sband25tt44[Order];
unsigned short sband25ty12[Order];
unsigned short sband25tr[Order];
unsigned short sband26tt37[Order];
unsigned short sband26ty3[Order];
unsigned short sband26tr[Order];
unsigned short sband27tt33[Order];
unsigned short sband27ty4[Order];
unsigned short sband27tr[Order];
unsigned short sband28tt43[Order];
unsigned short sband28ty13[Order];
unsigned short sband28tr[Order];
unsigned short sband29tt40[Order];
unsigned short sband29ty5[Order];
unsigned short sband29tr[Order];
unsigned short sband30tt42[Order];
unsigned short sband30ty9[Order];
unsigned short sband30tr[Order];
unsigned short sband31tt45[Order];
unsigned short sband31ty14[Order];
unsigned short sband31tr[Order];
unsigned short sband32tt41[Order];
unsigned short sband32ty8[Order];
unsigned short sband32tr[Order];

unsigned short online_sbx0[1];
unsigned short online_sbx1[1];
unsigned short online_sbx2[1];
unsigned short online_sbx3[1];
unsigned short online_sbx4[1];
unsigned short online_sbx5[1];
unsigned short online_sbx6[1];
unsigned short online_sbx7[1];


unsigned short online_sby0[1]={0};
unsigned short online_sby1[1]={0};
unsigned short online_sby2[1]={0};
unsigned short online_sby3[1]={0};
unsigned short online_sby4[1]={0};
unsigned short online_sby5[1]={0};
unsigned short online_sby6[1]={0};
unsigned short online_sby7[1]={0};
unsigned short online_sby8[1]={0};
unsigned short online_sby9[1]={0};
unsigned short online_sby10[1]={0};
unsigned short online_sby11[1]={0};
unsigned short online_sby12[1]={0};
unsigned short online_sby13[1]={0};
unsigned short online_sby14[1]={0};
unsigned short online_sby15[1]={0};
unsigned short online_sby16[1]={0};
unsigned short online_sby17[1]={0};
unsigned short online_sby18[1]={0};
unsigned short online_sby19[1]={0};
unsigned short online_sby20[1]={0};
unsigned short online_sby21[1]={0};

unsigned short online_sbt0[1]={0};
unsigned short online_sbt1[1]={0};
unsigned short online_sbt2[1]={0};
unsigned short online_sbt3[1]={0};
unsigned short online_sbt4[1]={0};
unsigned short online_sbt5[1]={0};
unsigned short online_sbt6[1]={0};
unsigned short online_sbt7[1]={0};
unsigned short online_sbt8[1]={0};
unsigned short online_sbt9[1]={0};
unsigned short online_sbt10[1]={0};
unsigned short online_sbt11[1]={0};
unsigned short online_sbt12[1]={0};
unsigned short online_sbt13[1]={0};
unsigned short online_sbt14[1]={0};
unsigned short online_sbt15[1]={0};
unsigned short online_sbt16[1]={0};
unsigned short online_sbt17[1]={0};
unsigned short online_sbt18[1]={0};
unsigned short online_sbt19[1]={0};
unsigned short online_sbt20[1]={0};
unsigned short online_sbt21[1]={0};
unsigned short online_sbt22[1]={0};
unsigned short online_sbt23[1]={0};
unsigned short online_sbt24[1]={0};
unsigned short online_sbt25[1]={0};
unsigned short online_sbt26[1]={0};
unsigned short online_sbt27[1]={0};
unsigned short online_sbt28[1]={0};
unsigned short online_sbt29[1]={0};
unsigned short online_sbt30[1]={0};
unsigned short online_sbt31[1]={0};
unsigned short online_sbt32[1]={0};
unsigned short online_sbt33[1]={0};
unsigned short online_sbt34[1]={0};
unsigned short online_sbt35[1]={0};
unsigned short online_sbt36[1]={0};
unsigned short online_sbt37[1]={0};
unsigned short online_sbt38[1]={0};
unsigned short online_sbt39[1]={0};
unsigned short online_sbt40[1]={0};
unsigned short online_sbt41[1]={0};
unsigned short online_sbt42[1]={0};
unsigned short online_sbt43[1]={0};
unsigned short online_sbt44[1]={0};
unsigned short online_sbt45[1]={0};
unsigned short online_sbt46[1]={0};
unsigned short online_sbt47[1]={0};
unsigned short online_sbt48[1]={0};
unsigned short online_sbt49[1]={0};
unsigned short online_sbt50[1]={0};
unsigned short online_sbt51[1]={0};
unsigned short online_sbt52[1]={0};
unsigned short online_sbt53[1]={0};
unsigned short online_sbt54[1]={0};
unsigned short online_sbt55[1]={0};
unsigned short online_sbt56[1]={0};
unsigned short online_sbt57[1]={0};
unsigned short online_sbt58[1]={0};
unsigned short online_sbt59[1]={0};
unsigned short online_sbt60[1]={0};
unsigned short online_sbt61[1]={0};
unsigned short online_sbt62[1]={0};
unsigned short online_sbt63[1]={0};
unsigned short online_sbt64[1]={0};
unsigned short online_sbt65[1]={0};
unsigned short online_sbt66[1]={0};
unsigned short online_sbt67[1]={0};

unsigned short online_sbs0[1]={0};;
unsigned short online_sbs1[1]={0};;
unsigned short online_sbs2[1]={0};
unsigned short online_sbs3[1]={0};
unsigned short online_sbs4[1]={0};
unsigned short online_sbs5[1]={0};
unsigned short online_sbs6[1]={0};
unsigned short online_sbs7[1]={0};
unsigned short online_sbs8[1]={0};

unsigned short online_sbz0[1]={0};
unsigned short online_sbz1[1]={0};
unsigned short online_sbz2[1]={0};
unsigned short online_sbz3[1]={0};
unsigned short online_sbz4[1]={0};
unsigned short online_sbz5[1]={0};
unsigned short online_sbz6[1]={0};
unsigned short online_sbz8[1]={0};
unsigned short online_sbz7[1]={0};
unsigned short online_sbz9[1]={0};
unsigned short online_sbz10[1]={0};
unsigned short online_sbz11[1]={0};
unsigned short online_sbz12[1]={0};
unsigned short online_sbz13[1]={0};
unsigned short online_sbz14[1]={0};
unsigned short online_sbz15[1]={0};
unsigned short online_sbz16[1]={0};
unsigned short online_sbz17[1]={0};


unsigned short after_mixcolumn0[Order];
unsigned short after_mixcolumn1[Order];
unsigned short after_mixcolumn2[Order];
unsigned short after_mixcolumn3[Order];
unsigned short after_mixcolumn4[Order];
unsigned short after_mixcolumn5[Order];
unsigned short after_mixcolumn6[Order];
unsigned short after_mixcolumn7[Order];


unsigned short after_shiftrows0[Order];
unsigned short after_shiftrows1[Order];
unsigned short after_shiftrows2[Order];
unsigned short after_shiftrows3[Order];
unsigned short after_shiftrows4[Order];
unsigned short after_shiftrows5[Order];
unsigned short after_shiftrows6[Order];
unsigned short after_shiftrows7[Order];


unsigned short online_after_shiftrows0[1];
unsigned short online_after_shiftrows1[1];
unsigned short online_after_shiftrows2[1];
unsigned short online_after_shiftrows3[1];
unsigned short online_after_shiftrows4[1];
unsigned short online_after_shiftrows5[1];
unsigned short online_after_shiftrows6[1];
unsigned short online_after_shiftrows7[1];

unsigned short online_after_mixcolumn0[1];
unsigned short online_after_mixcolumn1[1];
unsigned short online_after_mixcolumn2[1];
unsigned short online_after_mixcolumn3[1];
unsigned short online_after_mixcolumn4[1];
unsigned short online_after_mixcolumn5[1];
unsigned short online_after_mixcolumn6[1];
unsigned short online_after_mixcolumn7[1];


extern unsigned short sbxtest[Order];
extern unsigned short sbytest[Order];
extern unsigned short sbttest[Order];
extern unsigned short sband0txtest[Order];
extern unsigned short sband0tytest[Order];
extern unsigned short sband0tttest[Order];

extern unsigned short online_sbxtest[1];
extern unsigned short online_sbytest[1];
extern unsigned short online_sbttest[1];

extern unsigned short random_table[RANDOM_LENGTH / 2];
extern unsigned short sbx0[Order];
extern unsigned short sbx1[Order];
extern unsigned short sbx2[Order];
extern unsigned short sbx3[Order];
extern unsigned short sbx4[Order];
extern unsigned short sbx5[Order];
extern unsigned short sbx6[Order];
extern unsigned short sbx7[Order];

extern unsigned short sby0[Order];
extern unsigned short sby1[Order];
extern unsigned short sby2[Order];
extern unsigned short sby3[Order];
extern unsigned short sby4[Order];
extern unsigned short sby5[Order];
extern unsigned short sby6[Order];
extern unsigned short sby7[Order];
extern unsigned short sby8[Order];
extern unsigned short sby9[Order];
extern unsigned short sby10[Order];
extern unsigned short sby11[Order];
extern unsigned short sby12[Order];
extern unsigned short sby13[Order];
extern unsigned short sby14[Order];
extern unsigned short sby15[Order];
extern unsigned short sby16[Order];
extern unsigned short sby17[Order];
extern unsigned short sby18[Order];
extern unsigned short sby19[Order];
extern unsigned short sby20[Order];
extern unsigned short sby21[Order];

extern unsigned short sbt0[Order];
extern unsigned short sbt1[Order];
extern unsigned short sbt2[Order];
extern unsigned short sbt3[Order];
extern unsigned short sbt4[Order];
extern unsigned short sbt5[Order];
extern unsigned short sbt6[Order];
extern unsigned short sbt7[Order];
extern unsigned short sbt8[Order];
extern unsigned short sbt9[Order];
extern unsigned short sbt10[Order];
extern unsigned short sbt11[Order];
extern unsigned short sbt12[Order];
extern unsigned short sbt13[Order];
extern unsigned short sbt14[Order];
extern unsigned short sbt15[Order];
extern unsigned short sbt16[Order];
extern unsigned short sbt17[Order];
extern unsigned short sbt18[Order];
extern unsigned short sbt19[Order];
extern unsigned short sbt20[Order];
extern unsigned short sbt21[Order];
extern unsigned short sbt22[Order];
extern unsigned short sbt23[Order];
extern unsigned short sbt24[Order];
extern unsigned short sbt25[Order];
extern unsigned short sbt26[Order];
extern unsigned short sbt27[Order];
extern unsigned short sbt28[Order];
extern unsigned short sbt29[Order];
extern unsigned short sbt30[Order];
extern unsigned short sbt31[Order];
extern unsigned short sbt32[Order];
extern unsigned short sbt33[Order];
extern unsigned short sbt34[Order];
extern unsigned short sbt35[Order];
extern unsigned short sbt36[Order];
extern unsigned short sbt37[Order];
extern unsigned short sbt38[Order];
extern unsigned short sbt39[Order];
extern unsigned short sbt40[Order];
extern unsigned short sbt41[Order];
extern unsigned short sbt42[Order];
extern unsigned short sbt43[Order];
extern unsigned short sbt44[Order];
extern unsigned short sbt45[Order];
extern unsigned short sbt46[Order];
extern unsigned short sbt47[Order];
extern unsigned short sbt48[Order];
extern unsigned short sbt49[Order];
extern unsigned short sbt50[Order];
extern unsigned short sbt51[Order];
extern unsigned short sbt52[Order];
extern unsigned short sbt53[Order];
extern unsigned short sbt54[Order];
extern unsigned short sbt55[Order];
extern unsigned short sbt56[Order];
extern unsigned short sbt57[Order];
extern unsigned short sbt58[Order];
extern unsigned short sbt59[Order];
extern unsigned short sbt60[Order];
extern unsigned short sbt61[Order];
extern unsigned short sbt62[Order];
extern unsigned short sbt63[Order];
extern unsigned short sbt64[Order];
extern unsigned short sbt65[Order];
extern unsigned short sbt66[Order];
extern unsigned short sbt67[Order];

extern unsigned short sbs0[Order];
extern unsigned short sbs1[Order];
extern unsigned short sbs2[Order];
extern unsigned short sbs3[Order];
extern unsigned short sbs4[Order];
extern unsigned short sbs5[Order];
extern unsigned short sbs6[Order];
extern unsigned short sbs7[Order];
extern unsigned short sbs8[Order];

extern unsigned short sbz0[Order];
extern unsigned short sbz1[Order];
extern unsigned short sbz2[Order];
extern unsigned short sbz3[Order];
extern unsigned short sbz4[Order];
extern unsigned short sbz5[Order];
extern unsigned short sbz6[Order];
extern unsigned short sbz7[Order];
extern unsigned short sbz8[Order];
extern unsigned short sbz9[Order];
extern unsigned short sbz10[Order];
extern unsigned short sbz11[Order];
extern unsigned short sbz12[Order];
extern unsigned short sbz13[Order];
extern unsigned short sbz14[Order];
extern unsigned short sbz15[Order];
extern unsigned short sbz16[Order];
extern unsigned short sbz17[Order];

extern unsigned short sband1ty12[Order];
extern unsigned short sband1ty15[Order];
extern unsigned short sband1tr[Order];
extern unsigned short sband2ty3[Order];
extern unsigned short sband2ty6[Order];
extern unsigned short sband2tr[Order];
extern unsigned short sband3ty4[Order];
extern unsigned short sband3tx7[Order];
extern unsigned short sband3tr[Order];
extern unsigned short sband4ty13[Order];
extern unsigned short sband4ty16[Order];
extern unsigned short sband4tr[Order];
extern unsigned short sband5ty5[Order];
extern unsigned short sband5ty1[Order];
extern unsigned short sband5tr[Order];
extern unsigned short sband6ty2[Order];
extern unsigned short sband6ty7[Order];
extern unsigned short sband6tr[Order];
extern unsigned short sband7ty9[Order];
extern unsigned short sband7ty11[Order];
extern unsigned short sband7tr[Order];
extern unsigned short sband8ty14[Order];
extern unsigned short sband8ty17[Order];
extern unsigned short sband8tr[Order];
extern unsigned short sband9ty8[Order];
extern unsigned short sband9ty10[Order];
extern unsigned short sband9tr[Order];
extern unsigned short sband10tt21[Order];
extern unsigned short sband10tt23[Order];
extern unsigned short sband10tr[Order];
extern unsigned short sband11tt25[Order];
extern unsigned short sband11tt27[Order];
extern unsigned short sband11tr[Order];
extern unsigned short sband12tt31[Order];
extern unsigned short sband12tt30[Order];
extern unsigned short sband12tr[Order];
extern unsigned short sband13tt29[Order];
extern unsigned short sband13ty2[Order];
extern unsigned short sband13tr[Order];
extern unsigned short sband14tt24[Order];
extern unsigned short sband14tt35[Order];
extern unsigned short sband14tr[Order];
extern unsigned short sband15tt29[Order];
extern unsigned short sband15tt38[Order];
extern unsigned short sband15tr[Order];
extern unsigned short sband16tt29[Order];
extern unsigned short sband16ty7[Order];
extern unsigned short sband16tr[Order];
extern unsigned short sband17tt44[Order];
extern unsigned short sband17ty15[Order];
extern unsigned short sband17tr[Order];
extern unsigned short sband18tt37[Order];
extern unsigned short sband18ty6[Order];
extern unsigned short sband18tr[Order];
extern unsigned short sband19tt33[Order];
extern unsigned short sband19tx7[Order];
extern unsigned short sband19tr[Order];
extern unsigned short sband20tt43[Order];
extern unsigned short sband20ty16[Order];
extern unsigned short sband20tr[Order];
extern unsigned short sband21tt40[Order];
extern unsigned short sband21ty1[Order];
extern unsigned short sband21tr[Order];
extern unsigned short sband22tt42[Order];
extern unsigned short sband22ty11[Order];
extern unsigned short sband22tr[Order];
extern unsigned short sband23tt45[Order];
extern unsigned short sband23ty17[Order];
extern unsigned short sband23tr[Order];
extern unsigned short sband24tt41[Order];
extern unsigned short sband24ty10[Order];
extern unsigned short sband24tr[Order];
extern unsigned short sband25tt44[Order];
extern unsigned short sband25ty12[Order];
extern unsigned short sband25tr[Order];
extern unsigned short sband26tt37[Order];
extern unsigned short sband26ty3[Order];
extern unsigned short sband26tr[Order];
extern unsigned short sband27tt33[Order];
extern unsigned short sband27ty4[Order];
extern unsigned short sband27tr[Order];
extern unsigned short sband28tt43[Order];
extern unsigned short sband28ty13[Order];
extern unsigned short sband28tr[Order];
extern unsigned short sband29tt40[Order];
extern unsigned short sband29ty5[Order];
extern unsigned short sband29tr[Order];
extern unsigned short sband30tt42[Order];
extern unsigned short sband30ty9[Order];
extern unsigned short sband30tr[Order];
extern unsigned short sband31tt45[Order];
extern unsigned short sband31ty14[Order];
extern unsigned short sband31tr[Order];
extern unsigned short sband32tt41[Order];
extern unsigned short sband32ty8[Order];
extern unsigned short sband32tr[Order];


extern unsigned short online_sbx0[1];
extern unsigned short online_sbx1[1];
extern unsigned short online_sbx2[1];
extern unsigned short online_sbx3[1];
extern unsigned short online_sbx4[1];
extern unsigned short online_sbx5[1];
extern unsigned short online_sbx7[1];
extern unsigned short online_sbx6[1];

 
extern unsigned short online_sby0[1];
extern unsigned short online_sby1[1];
extern unsigned short online_sby2[1];
extern unsigned short online_sby3[1];
extern unsigned short online_sby4[1];
extern unsigned short online_sby5[1];
extern unsigned short online_sby6[1];
extern unsigned short online_sby7[1];
extern unsigned short online_sby8[1];
extern unsigned short online_sby9[1];
extern unsigned short online_sby10[1];
extern unsigned short online_sby11[1];
extern unsigned short online_sby12[1];
extern unsigned short online_sby13[1];
extern unsigned short online_sby14[1];
extern unsigned short online_sby15[1];
extern unsigned short online_sby16[1];
extern unsigned short online_sby17[1];
extern unsigned short online_sby18[1];
extern unsigned short online_sby19[1];
extern unsigned short online_sby20[1];
extern unsigned short online_sby21[1];
 
extern unsigned short online_sbt0[1];
extern unsigned short online_sbt1[1];
extern unsigned short online_sbt2[1];
extern unsigned short online_sbt3[1];
extern unsigned short online_sbt4[1];
extern unsigned short online_sbt5[1];
extern unsigned short online_sbt6[1];
extern unsigned short online_sbt7[1];
extern unsigned short online_sbt8[1];
extern unsigned short online_sbt9[1];
extern unsigned short online_sbt10[1];
extern unsigned short online_sbt11[1];
extern unsigned short online_sbt12[1];
extern unsigned short online_sbt13[1];
extern unsigned short online_sbt14[1];
extern unsigned short online_sbt15[1];
extern unsigned short online_sbt16[1];
extern unsigned short online_sbt17[1];
extern unsigned short online_sbt18[1];
extern unsigned short online_sbt19[1];
extern unsigned short online_sbt20[1];
extern unsigned short online_sbt21[1];
extern unsigned short online_sbt22[1];
extern unsigned short online_sbt23[1];
extern unsigned short online_sbt24[1];
extern unsigned short online_sbt25[1];
extern unsigned short online_sbt26[1];
extern unsigned short online_sbt27[1];
extern unsigned short online_sbt28[1];
extern unsigned short online_sbt29[1];
extern unsigned short online_sbt30[1];
extern unsigned short online_sbt31[1];
extern unsigned short online_sbt32[1];
extern unsigned short online_sbt33[1];
extern unsigned short online_sbt34[1];
extern unsigned short online_sbt35[1];
extern unsigned short online_sbt36[1];
extern unsigned short online_sbt37[1];
extern unsigned short online_sbt38[1];
extern unsigned short online_sbt39[1];
extern unsigned short online_sbt40[1];
extern unsigned short online_sbt41[1];
extern unsigned short online_sbt42[1];
extern unsigned short online_sbt43[1];
extern unsigned short online_sbt44[1];
extern unsigned short online_sbt45[1];
extern unsigned short online_sbt46[1];
extern unsigned short online_sbt47[1];
extern unsigned short online_sbt48[1];
extern unsigned short online_sbt49[1];
extern unsigned short online_sbt50[1];
extern unsigned short online_sbt51[1];
extern unsigned short online_sbt52[1];
extern unsigned short online_sbt53[1];
extern unsigned short online_sbt54[1];
extern unsigned short online_sbt55[1];
extern unsigned short online_sbt56[1];
extern unsigned short online_sbt57[1];
extern unsigned short online_sbt58[1];
extern unsigned short online_sbt59[1];
extern unsigned short online_sbt60[1];
extern unsigned short online_sbt61[1];
extern unsigned short online_sbt62[1];
extern unsigned short online_sbt63[1];
extern unsigned short online_sbt64[1];
extern unsigned short online_sbt65[1];
extern unsigned short online_sbt66[1];
extern unsigned short online_sbt67[1];

extern unsigned short online_sbs0[1];
extern unsigned short online_sbs1[1];
extern unsigned short online_sbs2[1];
extern unsigned short online_sbs3[1];
extern unsigned short online_sbs4[1];
extern unsigned short online_sbs5[1];
extern unsigned short online_sbs6[1];
extern unsigned short online_sbs7[1];

extern unsigned short online_sbz0[1];
extern unsigned short online_sbz1[1];
extern unsigned short online_sbz2[1];
extern unsigned short online_sbz3[1];
extern unsigned short online_sbz4[1];
extern unsigned short online_sbz5[1];
extern unsigned short online_sbz6[1];
extern unsigned short online_sbz8[1];
extern unsigned short online_sbz7[1];
extern unsigned short online_sbz9[1];
extern unsigned short online_sbz10[1];
extern unsigned short online_sbz11[1];
extern unsigned short online_sbz12[1];
extern unsigned short online_sbz13[1];
extern unsigned short online_sbz14[1];
extern unsigned short online_sbz15[1];
extern unsigned short online_sbz16[1];
extern unsigned short online_sbz17[1];

extern unsigned short after_mixcolumn0[Order];
extern unsigned short after_mixcolumn1[Order];
extern unsigned short after_mixcolumn2[Order];
extern unsigned short after_mixcolumn3[Order];
extern unsigned short after_mixcolumn4[Order];
extern unsigned short after_mixcolumn5[Order];
extern unsigned short after_mixcolumn6[Order];
extern unsigned short after_mixcolumn7[Order];

extern unsigned short after_shiftrows0[Order];
extern unsigned short after_shiftrows1[Order];
extern unsigned short after_shiftrows2[Order];
extern unsigned short after_shiftrows3[Order];
extern unsigned short after_shiftrows4[Order];
extern unsigned short after_shiftrows5[Order];
extern unsigned short after_shiftrows6[Order];
extern unsigned short after_shiftrows7[Order];

extern unsigned short online_after_mixcolumn0[1];
extern unsigned short online_after_mixcolumn1[1];
extern unsigned short online_after_mixcolumn2[1];
extern unsigned short online_after_mixcolumn3[1];
extern unsigned short online_after_mixcolumn4[1];
extern unsigned short online_after_mixcolumn5[1];
extern unsigned short online_after_mixcolumn6[1];
extern unsigned short online_after_mixcolumn7[1];

extern unsigned short online_after_shiftrows0[1];
extern unsigned short online_after_shiftrows1[1];
extern unsigned short online_after_shiftrows2[1];
extern unsigned short online_after_shiftrows3[1];
extern unsigned short online_after_shiftrows4[1];
extern unsigned short online_after_shiftrows5[1];
extern unsigned short online_after_shiftrows6[1];
extern unsigned short online_after_shiftrows7[1];